#!/bin/bash

MSG="$(git show --format='%B' -s $SHA1)"
ISSUE_NUMBER="$(echo $MSG | grep -o -E '[0-9]+')"

COMMENT=""
COMMENT="$COMMENT$(date) \n"
COMMENT="$COMMENT$(git config user.name) \n"
COMMENT="$COMMENT$(git diff --name-status HEAD HEAD~1) \n"
COMMENT="$COMMENT$MSG"
COMMENT="$(echo $COMMENT | tr -d '\n')"

curl -X POST -H "Accept: application/vnd.github.v3+json " -H "Authorization: token 4cd15e8b4b436706b3fe8c481ec83b811331676d" https://api.github.com/repos/andrefilho99/gitHooks/issues/$ISSUE_NUMBER/comments --data "{ \"body\":\"$COMMENT\"}"
