#!/bin/bash

COMMIT_MSG="$(git show --format='%B' -s $SHA1)"
ISSUE_NUMBER="$(echo $MSG | grep -o -E '[0-9]+')"

COMMENT=""
COMMENT="$COMMENT$(date) \n"
COMMENT="$COMMENT$(git config user.name) \n"
COMMENT="$COMMENT$(git diff --name-only HEAD HEAD~1) \n"
COMMENT="$COMMENT$COMMIT_MSG"
COMMENT="$(echo $COMMENT | tr -d '\n')"

curl -s -o nul -X POST -H "Accept: application/vnd.github.v3+json " -H "Authorization: token e2f78f524d1ad664a7cb0ddf142" https://api.github.com/repos/andrefilho99/gitHooks/issues/$ISSUE_NUMBER/comments --data "{ \"body\":\"$COMMENT\"}"
