#!/bin/bash

echo "Iniciando checagem do commit..."

MSG="$(cat $1)"
PATTERN="^#[0-9]*"
ISSUE_NUMBER="$(echo $MSG | grep -o -E '[0-9]+')"

if [[ $MSG =~ $PATTERN ]];then
        echo "Commit de acordo com as diretrizes estabelecidas!"
else
        echo "Commit não possui número de issue!"
        exit 1
fi

CURLARGS="-f -s -S -k"
API_URL="https://api.github.com/repos/andrefilho99/gitHooks/issues/$ISSUE_NUMBER/labels"
RAW_JSON="$(curl $CURLARGS $API_URL)"
DOING_PATTERN="doing"

if [[ $RAW_JSON =~ $DOING_PATTERN ]];then
        echo "Issue está em desenvolvimento!"
else
        echo "Adicione a label doing para realizar commits nessa issue!"
        exit 1
fi
