#!/bin/bash

COMMIT_MSG="$(cat $1)"
REGEX="^#[0-9]*"
ISSUE_NUMBER="$(echo $MSG | grep -o -E '[0-9]+')"

if [[ $COMMIT_MSG =~ $REGEX ]];then
        echo "Commit message is OK!"
else
        echo "There is no issue number within the commit message"
        exit 1
fi

CURLARGS="-f -s -S -k"
API_URL="https://api.github.com/repos/andrefilho99/gitHooks/issues/$ISSUE_NUMBER/labels"
RAW_JSON="$(curl $CURLARGS $API_URL)"
DOING_PATTERN="doing"

if [[ $RAW_JSON =~ $DOING_PATTERN ]];then
        echo "The issue has the label setted to DOING!"
else
        echo "Add/Change the issue label to DOING."
        exit 1
fi
